version: "3.5"
services:
  nginx:
    image: local/${APP_NAME}:v${APP_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
        max_attempts: 2
        window: 20s
      update_config:
        parallelism: 1
        delay: 2s
        monitor: 1s
        failure_action: rollback
        order: start-first
    ports:
      - "80"
