version: "3.5"
services:
  nginx:
    image: local/router:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
        max_attempts: 2
        window: 20s
      update_config:
        parallelism: 1
        delay: 2s
        monitor: 1s
        failure_action: rollback
        order: start-first
    ports:
      - "80:8080"
    configs:
      - source: update-config
        target: /update-config.sh
      - source: remove-config
        target: /remove-config.sh
configs:
  update-config:
    file: ./update-config.sh
  remove-config:
    file: ./remove-config.sh
